version: 2
sources:
  - name: boutique_a_source
    database: tyrok
    schema: operations
    tables:
      - name: deliverer
      - name: client
      - name: product
      - name: sales
  - name: boutique_a_raw
    database: tyrok
    schema: bronze_schema
    tables:
      - name: raw_deliverer
      - name: raw_client
      - name: raw_product
      - name: raw_sales
  - name: boutique_a_silver
    database: tyrok
    schema: silver_schema
    tables:
      - name: silver_deliverer
      - name: silver_client
      - name: silver_product
      - name: silver_sales
  - name: boutique_a_ia
    database: tyrok
    schema: ia_schema
    tables:
      - name: pred_deliverer_next_month
